### ISSUE TITLE
Bug in Item.class.php

### ISSUE THREAD

**Issue by WoZ** [chrisjameskirkham/memcache-viewer#1]
There are error on index page
Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM

In classes/Item.class.php on line 46 you should change $this::getRemainingTime to self::getRemainingTime.

getRemainingTime declared as static method, so you should use self:: for method calling. For non-static methods use $this->

**Comment by chrisjameskirkham** [comment]
Thanks for that, you're right.

I've never noticed the issue before -- must be a PHP configuration/version issue somewhere (or something). I'll get that changed.

Thanks again,
Chris

**Comment by WoZ** [comment]
By the way, else one))
index.php, line 5
When $_SESSION['logged_in'] isn't set php generates notice.

I suggest replace with 
if (!isset($_SESSION['logged_in'])){

Thats all. Thanks for app)

**Comment by chrisjameskirkham** [comment]
Thanks for that one too!

Glad it was of some use.

Cheers,
Chris
